POST {{host}}/api/queries/39/results
Accept: */*
Cache-Control: no-cache
Authorization: Key meayFBZn9UDMdYLpV5vzkNcKEvEWvUTkc3QNrItr

{"parameters":{"bucket":"'vnazota'","_part":"auto"}}

###

GET {{host}}/api/job/abc
Accept: */*
Cache-Control: no-cache
Authorization: Key meayFBZn9UDMdYLpV5vzkNcKEvEWvUTkc3QNrItr

###

POST {{host}}/api/queries/52/results?crashOnEmpty=1
Accept: */*
Cache-Control: no-cache
Authorization: Key meayFBZn9UDMdYLpV5vzkNcKEvEWvUTkc3QNrItr

{"parameters":{"bucket":"'vnazota'","time":"2021-11-01"}}

