POST {{host}}/api/queries/39/results
Accept: */*
Cache-Control: no-cache
Authorization: Key meayFBZn9UDMdYLpV5vzkNcKEvEWvUTkc3QNrItr

{"parameters":{"bucket":"'boxes'","_part":"auto"}}

###

GET {{host}}/api/job/abc
Accept: */*
Cache-Control: no-cache
Authorization: Key meayFBZn9UDMdYLpV5vzkNcKEvEWvUTkc3QNrItr

###

POST {{host}}/api/queries/52/results?crashOnEmpty=1
Accept: */*
Cache-Control: no-cache
Authorization: Key meayFBZn9UDMdYLpV5vzkNcKEvEWvUTkc3QNrItr

{"parameters":{"bucket":"'vnazota','boxstudio'","time":"2022-03-01"}}

###


POST {{host}}/api/queries/56/results
Accept: */*
Cache-Control: no-cache
Authorization: Key meayFBZn9UDMdYLpV5vzkNcKEvEWvUTkc3QNrItr

{"parameters":{"day":"2022-03-06"}}

###
